//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cactus.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cactus_Vistavka
    {
        public int Id_vistavka { get; set; }
        public Nullable<int> Id_cactus { get; set; }
        public Nullable<int> Id_vistav { get; set; }
    
        public virtual Cactusi Cactus { get; set; }
        public virtual Vistavka Vistavka { get; set; }
    }
}
