//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cactus.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public int Id_login { get; set; }
        public string Login1 { get; set; }
        public string Password { get; set; }
        public Nullable<int> Id_user { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
